title: Cameroon Budget Inquirer
openspendingjs: '/js/openspendingjs'
url: http://cameroon.openspending.org
openspendingUrl: https://openspending.org
budgetsDataset: "cm-budgets"
pibDataset: "cm-pib"

locales:
  en:
    title: "Cameroon Budget Inquirer"
    home: "Home"
    about: "About"
    why: "Why Budget Transparency"
    nationalbudget: "National Investment Budget"
    nwbudget: "Regional Investment Budget"
    transparencyindex: "Local Budget Transparency Index"
    councilbudget: "Council Budget"
    collaborationbetween: "is a collaboration between the"
    worldbank: "World Bank"
    andthe: "and the"
    withcontribution: "with the contribution of"
    assoal: " ASSOAL"
    intro: "intro and background"
    contribute: "Contribute"
    localcouncilinfo: "local council information"
    sourcecode: "Source code repository"

  fr:
    title: "Explorateur budgétaire"
    home: "Accueil"
    about: "À propos "
    why: "La transparence budgétaire"
    nationalbudget: "Budget public d'investissement"
    nwbudget: "Budget régional d'investissement"
    transparencyindex: "Indice de transparence"
    councilbudget: "Budget de la commune"
    collaborationbetween: "est une coopération entre"
    worldbank: "la Banque Mondiale"
    andthe: "et"
    withcontribution: "avec la contribution d'"
    assoal: "ASSOAL"
    intro: "introduction et contexte"
    contribute: "Contribuer"
    localcouncilinfo: "aux informations sur les communes"
    sourcecode: "Code source"
